# .streamlit/config.toml

[theme]
primaryColor = "#7F38F2"  # Purple accent color
backgroundColor = "#0D0D0D"  # Dark background
secondaryBackgroundColor = "#1A1A1A"  # Sidebar background color
textColor = "#E8E8E8"  # Text color
font = "sans serif"  # Font family